### ISSUE TITLE
Session issue after API call

### ISSUE THREAD

**Issue by sagikazarmark** [orocrm/platform#451]
There is a strange issue when using Nelmio API doc: Oro does not load anymore. I traced the issue to this error in the PHP log:

`PHP message: PHP Fatal error:  Call to a member function getId() on null in HOME/var/cache/prod/classes.php on line 8266`

I checked that line as well:

`$this->getOrganizationManager()->getOrganizationById($token->getOrganizationContext()->getId())`

Actually I believe it's not nelmio itself, because just loading the API doc does not cause this error. However, when sending an API request to a custom API endpoint,  from that point clicking anywhere on the site ends up in a 500 error (even the api doc).

It seems to me that the session to be badly saved? Is that possible?

Currently the solution is to clear the cookies, because there is no other way to get back to oro.

Any ideas?

**Comment by sagikazarmark** [comment]
In the meantime, I found that the API doc sandbox sends the PHPSESSID cookie to the server, which messes up the session. I don't know if it is a Nelmio issue or not (and if it's fixed or not, since the nelmio version is quite old here), but it's an anti-pattern (or rather a bug). REST is stateless.

**Comment by yurio** [comment]
Hi, @sagikazarmark. This issue was fixed and will be available in nearest release

**Comment by sagikazarmark** [comment]
Can you reference the fix here? Then we can probably close the issue.

**Comment by artml** [comment]
@sagikazarmark not sure if we might find the exact commit. But you don't experience the issue anymore, right?

**Comment by sagikazarmark** [comment]
On 1.9.2 I still have the issue. I asked for reference to see whether this will be solved in the 1.9.x versions or not.

**Comment by sergeyz** [comment]
Hi, @sagikazarmark, I thinks its 0882c20ceb4937ced1e67f97e21d8bdaebda906b
Make sure you don't override `api_wsse_secured` firewall in `app/config/security.yml`

**Comment by sagikazarmark** [comment]
This might be related too: https://github.com/orocrm/crm/issues/191

**Comment by sagikazarmark** [comment]
I can confirm that this issue is solved.
